#-------------------------------------------------------------------------
#
# $Id: Makefile,v 1.1.1.1 2003/04/17 23:00:54 sailesh Exp $
#
#-------------------------------------------------------------------------
subdir = src/backend/utils/mb/conversion_procs/utf8_and_win874
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		:= utf8_and_win874

include $(srcdir)/../proc.mk
