#-------------------------------------------------------------------------
#
# $Id: Makefile,v 1.1.1.1 2003/04/17 23:00:53 sailesh Exp $
#
#-------------------------------------------------------------------------
subdir = src/backend/utils/mb/conversion_procs/euc_kr_and_mic
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		:= euc_kr_and_mic

include $(srcdir)/../proc.mk
