# $Header: /project/eecs/db/cvsroot/postgres/contrib/string/Makefile,v 1.1.1.2 2003/04/17 22:34:53 sailesh Exp $

subdir = contrib/string
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = string_io
DATA_built = string_io.sql
DOCS = README.string_io

include $(top_srcdir)/contrib/contrib-global.mk
