# $Header: /project/eecs/db/cvsroot/postgres/contrib/dbmirror/Makefile,v 1.1.1.1 2003/04/17 22:33:51 sailesh Exp $

subdir = contrib/dbmirror
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = pending
DOCS = README.dbmirror

include $(top_srcdir)/contrib/contrib-global.mk
