# $Header: /project/eecs/db/cvsroot/postgres/contrib/xml/Makefile,v 1.1.1.2 2003/04/17 22:37:42 sailesh Exp $

subdir = contrib/xml
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULE_big = pgxml_dom
OBJS = pgxml_dom.o
SHLIB_LINK = -lxml2
DATA_built = pgxml_dom.sql
DOCS = README.pgxml

include $(top_srcdir)/contrib/contrib-global.mk
