#define yy_create_buffer plpgsql_base_yy_create_buffer
#define yy_delete_buffer plpgsql_base_yy_delete_buffer
#define yy_scan_buffer plpgsql_base_yy_scan_buffer
#define yy_scan_string plpgsql_base_yy_scan_string
#define yy_scan_bytes plpgsql_base_yy_scan_bytes
#define yy_flex_debug plpgsql_base_yy_flex_debug
#define yy_init_buffer plpgsql_base_yy_init_buffer
#define yy_flush_buffer plpgsql_base_yy_flush_buffer
#define yy_load_buffer_state plpgsql_base_yy_load_buffer_state
#define yy_switch_to_buffer plpgsql_base_yy_switch_to_buffer
#define yyin plpgsql_base_yyin
#define yyleng plpgsql_base_yyleng
#define yylex plpgsql_base_yylex
#define yyout plpgsql_base_yyout
#define yyrestart plpgsql_base_yyrestart
#define yytext plpgsql_base_yytext
#define yylineno plpgsql_base_yylineno

#line 20 "pl_scan.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yytext_ptr -= yy_more_len; \
	yyleng = (int) (yy_cp - yytext_ptr); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
static yyconst short int yy_acclist[360] =
    {   0,
       80,   80,   83,   81,   82,   70,   81,   82,   70,   82,
       81,   82,   81,   82,   76,   81,   82,   81,   82,   81,
       82,   81,   82,   68,   81,   82,   81,   82,    2,   81,
       82,   52,   81,   82,   52,   81,   82,   52,   81,   82,
       52,   81,   82,   52,   81,   82,   52,   81,   82,   52,
       81,   82,   52,   81,   82,   52,   81,   82,   52,   81,
       82,   52,   81,   82,   52,   81,   82,   52,   81,   82,
       52,   81,   82,   52,   81,   82,   52,   81,   82,   52,
       81,   82,   81,   82,   80,   82,   79,   82,   82,   75,
       82,   74,   82,   75,   82,   70,   69,   52,   69,   60,

       71,    3,   72,   68,    1,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   23,   52,   24,   52,   27,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   45,   52,
       52,   52,   52,   80,   78,   77,   73,   52,   71,   53,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   15,   52,   52,   52,   52,   52,   20,   52,   52,
       22,   52,   52,   52,   28,   52,   52,   52,   31,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   61,   53,   53,   52,

       52,   52,   52,   52,   52,   52,   52,   52,   51,   52,
       13,   52,   52,   52,   52,   18,   52,   52,   21,   52,
       25,   52,   26,   52,   29,   52,   30,   52,   52,   33,
       52,   34,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   44,   52,   46,   52,   52,   48,   52,   52,
       61,   61,   54,    4,   52,    5,   52,    6,   52,   52,
       52,    9,   52,   52,   52,   52,   14,   52,   52,   52,
       19,   52,   52,   52,   36,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   49,   52,   62,   55,   54,   54,
       52,    8,   52,   52,   52,   52,   52,   52,   32,   52,

       52,   37,   52,   38,   52,   52,   40,   52,   52,   52,
       43,   52,   52,   63,   62,   62,   52,   10,   52,   11,
       52,   52,   52,   17,   52,   35,   52,   52,   41,   52,
       52,   47,   52,   50,   56,    7,   52,   52,   52,   52,
       52,   64,   58,   52,   16,   52,   52,   42,   52,   66,
       57,   52,   39,   52,   65,   59,   12,   52,   67
    } ;

static yyconst short int yy_accept[339] =
    {   0,
        1,    1,    1,    2,    3,    3,    3,    4,    6,    9,
       11,   13,   15,   18,   20,   22,   24,   27,   29,   32,
       35,   38,   41,   44,   47,   50,   53,   56,   59,   62,
       65,   68,   71,   74,   77,   80,   83,   85,   87,   89,
       90,   92,   94,   96,   97,   98,   98,  100,  101,  102,
      103,  104,  105,  106,  106,  106,  106,  107,  108,  109,
      110,  111,  112,  113,  114,  115,  116,  117,  118,  119,
      120,  121,  122,  124,  126,  128,  129,  130,  131,  132,
      133,  134,  135,  136,  137,  138,  139,  141,  142,  143,
      144,  144,  145,  146,  147,  148,  149,  149,  149,  149,

      149,  150,  150,  150,  150,  150,  151,  152,  153,  154,
      155,  156,  157,  158,  159,  160,  161,  162,  164,  165,
      166,  167,  168,  170,  171,  173,  174,  175,  177,  178,
      179,  181,  182,  183,  184,  185,  186,  187,  188,  189,
      190,  191,  192,  193,  194,  195,  196,  197,  197,  197,
      197,  197,  197,  198,  198,  198,  198,  199,  199,  199,
      199,  200,  201,  202,  203,  204,  205,  206,  207,  208,
      209,  211,  213,  214,  215,  216,  218,  219,  221,  223,
      225,  227,  229,  230,  232,  234,  235,  236,  237,  238,
      239,  240,  241,  242,  243,  245,  247,  248,  250,  251,

      251,  251,  251,  251,  252,  252,  252,  252,  253,  253,
      253,  253,  253,  253,  253,  254,  256,  258,  260,  261,
      262,  264,  265,  266,  267,  269,  270,  271,  273,  274,
      275,  277,  278,  279,  280,  281,  282,  283,  284,  285,
      287,  287,  287,  287,  287,  287,  287,  287,  288,  288,
      289,  289,  289,  289,  290,  290,  290,  291,  292,  294,
      295,  296,  297,  298,  299,  301,  302,  304,  306,  307,
      309,  310,  311,  313,  314,  314,  314,  315,  315,  315,
      315,  316,  316,  316,  317,  317,  317,  317,  317,  318,
      320,  322,  323,  324,  326,  328,  329,  331,  332,  334,

      335,  335,  335,  335,  335,  335,  335,  336,  336,  338,
      339,  340,  341,  342,  342,  342,  343,  343,  344,  344,
      344,  345,  347,  348,  350,  351,  351,  351,  351,  352,
      353,  355,  355,  356,  357,  359,  360,  360
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    7,    8,    1,    9,    1,
        1,   10,    1,    1,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,    1,    1,
       16,    1,    1,    1,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   28,   29,   30,   31,   32,   33,
       28,   34,   35,   36,   37,   38,   39,   40,   41,   28,
        1,   17,    1,    1,   18,    1,   19,   20,   21,   22,

       23,   24,   25,   26,   27,   28,   28,   29,   30,   31,
       32,   33,   28,   34,   35,   36,   37,   38,   39,   40,
       41,   28,    1,    1,    1,    1,    1,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,

       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28
    } ;

static yyconst int yy_meta[42] =
    {   0,
        1,    2,    3,    4,    5,    1,    1,    6,    7,    1,
        1,    8,    1,    6,    1,    1,    7,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2
    } ;

static yyconst short int yy_base[358] =
    {   0,
        0,  764,   33,   34,   42,   43,  769,  771,   45,   52,
       54,  754,  771,  756,  754,  755,  750,  747,  771,   58,
       61,   45,   43,   54,   47,   63,   56,   65,   69,   70,
       38,   59,   85,   80,   84,   86,  730,    0,  752,    0,
      771,  771,  747,  116,  754,  753,  119,  126,    0,  771,
      771,  743,  771,  133,  108,  144,  727,  123,  114,  122,
      124,   77,  136,  139,  103,  132,  137,  148,  134,  144,
      147,  145,  726,  156,  725,  157,  143,  155,  724,  164,
      161,  135,  167,  165,  723,  177,  722,  168,  178,  186,
      717,    0,  771,  771,  771,  214,  744,  221,  174,  232,

        0,  716,  706,  236,  741,  240,  192,  201,  185,  216,
      218,  217,  716,  230,  202,  227,  234,  715,  235,  241,
      236,  245,  714,  238,  713,  244,  246,  712,  248,  250,
      242,  711,  251,  226,  254,  255,  266,  259,  261,  268,
      274,  270,  271,  278,  275,  279,  710,  702,  705,  695,
      309,  730,  313,  695,  700,  727,  324,  331,  284,  342,
      346,  295,  309,  308,  323,  290,  280,  322,  324,  326,
      702,  701,  336,  333,  327,  700,  341,  699,  698,  697,
      696,  695,  342,  694,  693,  340,  345,  344,  346,  692,
      348,  350,  359,  360,  691,  690,  356,  689,  363,  690,

      677,  682,  709,  391,  398,  371,  409,  413,  677,  689,
      679,  669,  424,  704,  416,  679,  678,  677,  368,  375,
      676,  401,  675,  402,  674,  362,  403,  673,  413,  404,
      672,  415,  417,  412,  414,  418,  420,  421,  425,  671,
      667,  662,  674,  664,  654,  456,  689,  460,  652,  771,
      653,  658,  685,  467,  474,  653,  477,  436,  659,  460,
      437,  455,  459,  464,  658,  393,  657,  656,  473,  655,
      469,  466,  654,  426,  651,  640,  771,  641,  646,  673,
      502,  509,  641,  512,  643,  638,  638,  599,  465,  609,
      596,  489,  467,  594,  570,  468,  569,  490,  553,  771,

      545,  534,  545,  496,  513,  494,  771,  501,  480,  495,
      497,  500,  494,  485,  433,  771,  375,  771,  357,  319,
      510,  294,  511,  265,  771,  199,  176,  103,  771,  503,
       55,   35,  771,  771,   15,  771,  771,  540,  548,  556,
      563,  571,  579,  587,  595,  602,  606,  611,  618,  626,
      633,  640,  644,  649,  656,  662,  669
    } ;

static yyconst short int yy_def[358] =
    {   0,
      337,    1,  338,  338,  339,  339,  337,  337,  337,  337,
      340,  337,  337,  337,  337,  337,  337,  337,  337,  341,
      341,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,  337,  342,  337,  343,
      337,  337,  337,  337,  344,  344,  337,  337,  345,  337,
      337,  337,  337,  337,  337,  346,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
      337,  342,  337,  337,  337,  337,  344,  337,  337,  347,

      345,  337,  337,  346,  348,  349,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,  337,  337,  337,
      347,  350,  351,  337,  337,  348,  337,  337,  337,  352,
      349,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,  337,

      337,  337,  350,  337,  337,  337,  353,  351,  337,  337,
      337,  337,  352,  354,  355,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
      337,  337,  337,  337,  337,  353,  356,  357,  337,  337,
      337,  337,  354,  337,  337,  337,  355,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,  337,  337,  337,  337,  337,  356,
      337,  337,  337,  357,  337,  337,  337,  337,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,  337,

      337,  337,  337,  337,  337,  337,  337,  337,   21,   21,
       21,   21,   21,  337,  337,  337,  337,  337,  337,  337,
       21,   21,   21,   21,  337,  337,  337,  337,  337,   21,
       21,  337,  337,  337,   21,  337,    0,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337
    } ;

static yyconst short int yy_nxt[813] =
    {   0,
        8,    9,   10,    9,   11,    8,   12,    8,   13,    8,
       14,   15,   16,   17,   18,   19,    8,   20,   21,   22,
       23,   24,   25,   26,   27,   20,   28,   20,   29,   20,
       30,   31,   32,   33,   34,   35,   20,   20,   36,   20,
       20,   39,   39,   57,   42,   42,   44,   44,   44,   40,
       40,   43,   43,   44,   44,   44,   46,  336,   47,   54,
       54,   54,   54,   54,   54,   55,   57,   59,   55,   56,
       80,   60,   56,   57,   61,   66,   63,   67,   72,   62,
       64,   81,   57,   57,   57,   69,   68,   57,   73,   58,
       65,   57,   77,   57,   70,   74,   71,   57,   57,   75,

       76,   78,   85,   82,   89,   57,   79,   83,   57,   86,
      111,   90,   57,   57,   57,   87,   84,   44,   44,   44,
       54,   54,   54,   97,   88,  334,   55,   98,   98,   98,
       56,   57,  116,   99,   54,   54,   54,  100,  108,   48,
       55,  102,   57,  103,   56,  104,  104,  104,  105,  107,
       57,   57,   57,  109,  110,  112,  113,  115,  118,  114,
       57,  135,   57,   57,   57,   57,  117,   57,  119,  122,
      120,   57,   57,   57,  121,   57,   57,  123,  124,  126,
      125,  128,  130,   57,   57,   57,  133,  136,  129,   57,
      131,  127,   57,   57,  134,   57,   57,  137,  333,  143,

      144,  138,  139,  141,  140,   57,   57,  149,  146,  150,
      162,  145,  147,   57,   57,   54,   54,   54,   97,  164,
       57,   55,   98,   98,   98,   56,  170,  163,   99,   57,
       57,  332,  100,  151,  151,  151,  152,  104,  104,  104,
      105,  158,  158,  158,   57,   57,   57,  159,  169,  186,
      165,  160,  166,  167,   57,   57,  172,  174,   57,  171,
      173,  175,   57,   57,   57,  177,   57,  178,  183,   57,
       57,  176,   57,   57,   57,  179,   57,  180,   57,   57,
      181,  185,   57,   57,  189,  182,  188,   57,  187,   57,
      192,  193,  194,   57,   57,  190,   57,  191,   57,   57,

      196,  195,   57,   57,  221,  197,   57,   57,   57,  198,
      151,  151,  151,  152,  205,  205,  205,  211,   57,  212,
      206,  220,   57,   57,  207,  158,  158,  158,  105,  216,
      218,  159,  158,  158,  158,  160,   57,   57,  159,  217,
      222,  329,  160,  213,  213,  213,  214,  158,  158,  158,
       57,   57,   57,  159,   57,   57,  224,  160,  219,  225,
      223,   57,  229,  227,   57,  226,  228,  231,   57,   57,
       57,  230,   57,   57,   57,  233,   57,  232,   57,  237,
      238,  235,  239,  236,   57,  240,  258,   57,   57,  328,
       57,   57,  205,  205,  205,  152,   57,  263,  206,  205,

      205,  205,  207,   57,  244,  206,  245,  327,  259,  207,
      246,  246,  246,  247,  205,  205,  205,  255,  255,  255,
      206,   57,  295,  256,  207,  213,  213,  213,  214,   57,
       57,   57,   57,  262,  260,  265,  267,  266,  264,  268,
       57,   57,   57,   57,  270,   57,   57,  269,   57,   57,
      299,  272,  271,   57,   57,  274,  273,  246,  246,  246,
      247,  282,  282,  282,   57,   57,  289,  283,  255,  255,
      255,  214,  291,  326,  256,  255,  255,  255,  255,  255,
      255,  256,  290,   57,  256,  293,  294,   57,   57,  292,
      296,  297,   57,   57,   57,   57,   57,   57,  311,  312,

      309,   57,  298,  282,  282,  282,  247,  325,   57,  283,
      282,  282,  282,  282,  282,  282,  283,   57,   57,  283,
      313,  321,   57,   57,  310,   57,  323,  322,   57,  324,
      330,   57,  331,  320,  319,  318,  317,  335,   57,   57,
       38,   38,   38,   38,   38,   38,   38,   38,   41,   41,
       41,   41,   41,   41,   41,   41,   45,   45,   45,   45,
       45,   45,   45,   45,   57,   57,   57,  316,   57,  315,
       57,   92,   92,   92,   92,   92,   92,  314,   92,   94,
       94,   57,   94,   94,   94,   94,   94,   46,   46,   46,
       46,   46,   46,   46,   46,  101,  101,   57,   57,  101,

      101,  101,  101,  106,  106,  106,  106,  153,  153,  153,
      153,  156,  156,  156,  156,  156,  156,  156,  156,  161,
      161,  161,   57,  161,   57,  161,  203,  203,  203,  203,
      203,  203,  203,  203,  208,  208,  208,   57,  208,  308,
      208,  215,  215,  215,  215,  248,  248,  248,  248,  253,
      253,  253,  253,  253,  253,  253,  253,  257,  257,  257,
      307,  257,  280,  280,  280,  280,  280,  280,  280,  280,
      284,  284,  284,  306,  284,  305,  304,  281,  303,  302,
      301,  300,   57,   57,   57,   57,   57,   57,  288,  254,
      287,  286,  285,  281,  279,  278,  277,  276,  275,   57,

       57,   57,   57,  261,   57,   57,   57,   57,  254,  252,
      251,  250,  249,  204,  243,  242,  241,   57,   57,   57,
      234,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,  157,  210,  209,  204,  202,  201,  200,  199,  184,
       57,   57,   57,   57,  168,  157,  155,  154,   96,  148,
       57,  142,  132,   57,   57,   57,   52,   96,   96,   95,
       93,   91,   53,   52,   51,   50,   49,   48,  337,   37,
        7,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,

      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337
    } ;

static yyconst short int yy_chk[813] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,  335,    5,    6,    9,    9,    9,    3,
        4,    5,    6,   10,   10,   10,   11,  332,   11,   20,
       20,   20,   21,   21,   21,   20,   31,   22,   21,   20,
       31,   23,   21,   22,   23,   25,   24,   25,   27,   23,
       24,   32,   24,  331,   27,   26,   25,   32,   28,   21,
       24,   26,   30,   28,   26,   28,   26,   29,   30,   28,

       29,   30,   34,   33,   36,   62,   30,   33,   34,   35,
       62,   36,   35,   33,   36,   35,   33,   44,   44,   44,
       47,   47,   47,   47,   35,  328,   47,   48,   48,   48,
       47,   65,   65,   48,   54,   54,   54,   48,   59,   48,
       54,   55,   59,   55,   54,   56,   56,   56,   56,   58,
       60,   58,   61,   60,   61,   63,   63,   64,   67,   63,
       66,   82,   69,   82,   63,   67,   66,   64,   68,   69,
       68,   77,   70,   72,   68,   71,   68,   70,   71,   74,
       72,   76,   77,   78,   74,   76,   80,   83,   76,   81,
       78,   74,   80,   84,   81,   83,   88,   83,  327,   86,

       88,   83,   83,   84,   83,   86,   89,   99,   90,   99,
      107,   89,   90,  109,   90,   96,   96,   96,   96,  109,
      107,   96,   98,   98,   98,   96,  115,  108,   98,  108,
      115,  326,   98,  100,  100,  100,  100,  104,  104,  104,
      104,  106,  106,  106,  110,  112,  111,  106,  114,  134,
      110,  106,  111,  112,  134,  116,  117,  119,  114,  116,
      117,  120,  117,  119,  121,  122,  124,  124,  131,  120,
      131,  121,  126,  122,  127,  126,  129,  127,  130,  133,
      129,  133,  135,  136,  137,  130,  136,  138,  135,  139,
      140,  141,  142,  324,  137,  138,  140,  139,  142,  143,

      144,  143,  141,  145,  167,  145,  144,  146,  167,  146,
      151,  151,  151,  151,  153,  153,  153,  159,  166,  159,
      153,  166,  322,  162,  153,  157,  157,  157,  157,  162,
      164,  157,  158,  158,  158,  157,  164,  163,  158,  163,
      168,  320,  158,  160,  160,  160,  160,  161,  161,  161,
      168,  165,  169,  161,  170,  175,  170,  161,  165,  173,
      169,  174,  183,  175,  173,  174,  177,  187,  186,  177,
      183,  186,  188,  187,  189,  189,  191,  188,  192,  193,
      194,  191,  197,  192,  197,  199,  219,  193,  194,  319,
      226,  199,  204,  204,  204,  204,  219,  226,  204,  205,

      205,  205,  204,  220,  206,  205,  206,  317,  220,  205,
      207,  207,  207,  207,  208,  208,  208,  215,  215,  215,
      208,  266,  266,  215,  208,  213,  213,  213,  213,  222,
      224,  227,  230,  224,  222,  229,  232,  230,  227,  233,
      234,  229,  235,  232,  235,  233,  236,  234,  237,  238,
      274,  237,  236,  239,  274,  239,  238,  246,  246,  246,
      246,  248,  248,  248,  258,  261,  258,  248,  254,  254,
      254,  254,  261,  315,  254,  255,  255,  255,  257,  257,
      257,  255,  260,  262,  257,  263,  264,  263,  260,  262,
      269,  271,  264,  289,  272,  293,  296,  271,  293,  296,

      289,  269,  272,  281,  281,  281,  281,  314,  309,  281,
      282,  282,  282,  284,  284,  284,  282,  292,  298,  284,
      298,  310,  313,  310,  292,  311,  312,  311,  312,  313,
      321,  330,  323,  308,  306,  305,  304,  330,  321,  323,
      338,  338,  338,  338,  338,  338,  338,  338,  339,  339,
      339,  339,  339,  339,  339,  339,  340,  340,  340,  340,
      340,  340,  340,  340,  341,  341,  341,  303,  341,  302,
      341,  342,  342,  342,  342,  342,  342,  301,  342,  343,
      343,  299,  343,  343,  343,  343,  343,  344,  344,  344,
      344,  344,  344,  344,  344,  345,  345,  297,  295,  345,

      345,  345,  345,  346,  346,  346,  346,  347,  347,  347,
      347,  348,  348,  348,  348,  348,  348,  348,  348,  349,
      349,  349,  294,  349,  291,  349,  350,  350,  350,  350,
      350,  350,  350,  350,  351,  351,  351,  290,  351,  288,
      351,  352,  352,  352,  352,  353,  353,  353,  353,  354,
      354,  354,  354,  354,  354,  354,  354,  355,  355,  355,
      287,  355,  356,  356,  356,  356,  356,  356,  356,  356,
      357,  357,  357,  286,  357,  285,  283,  280,  279,  278,
      276,  275,  273,  270,  268,  267,  265,  259,  256,  253,
      252,  251,  249,  247,  245,  244,  243,  242,  241,  240,

      231,  228,  225,  223,  221,  218,  217,  216,  214,  212,
      211,  210,  209,  203,  202,  201,  200,  198,  196,  195,
      190,  185,  184,  182,  181,  180,  179,  178,  176,  172,
      171,  156,  155,  154,  152,  150,  149,  148,  147,  132,
      128,  125,  123,  118,  113,  105,  103,  102,   97,   91,
       87,   85,   79,   75,   73,   57,   52,   46,   45,   43,
       39,   37,   18,   17,   16,   15,   14,   12,    7,    2,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,

      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scan.l"
#define INITIAL 0
#line 2 "scan.l"
/**********************************************************************
 * scan.l		- Scanner for the PL/pgSQL
 *			  procedural language
 *
 * IDENTIFICATION
 *    $Header: /project/eecs/db/cvsroot/postgres/src/pl/plpgsql/src/scan.l,v 1.2 2004/03/24 08:11:35 chungwu Exp $
 *
 *    This software is copyrighted by Jan Wieck - Hamburg.
 *
 *    The author hereby grants permission  to  use,  copy,  modify,
 *    distribute,  and  license this software and its documentation
 *    for any purpose, provided that existing copyright notices are
 *    retained  in  all  copies  and  that  this notice is included
 *    verbatim in any distributions. No written agreement, license,
 *    or  royalty  fee  is required for any of the authorized uses.
 *    Modifications to this software may be  copyrighted  by  their
 *    author  and  need  not  follow  the licensing terms described
 *    here, provided that the new terms are  clearly  indicated  on
 *    the first page of each file where they apply.
 *
 *    IN NO EVENT SHALL THE AUTHOR OR DISTRIBUTORS BE LIABLE TO ANY
 *    PARTY  FOR  DIRECT,   INDIRECT,   SPECIAL,   INCIDENTAL,   OR
 *    CONSEQUENTIAL   DAMAGES  ARISING  OUT  OF  THE  USE  OF  THIS
 *    SOFTWARE, ITS DOCUMENTATION, OR ANY DERIVATIVES THEREOF, EVEN
 *    IF  THE  AUTHOR  HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH
 *    DAMAGE.
 *
 *    THE  AUTHOR  AND  DISTRIBUTORS  SPECIFICALLY   DISCLAIM   ANY
 *    WARRANTIES,  INCLUDING,  BUT  NOT  LIMITED  TO,  THE  IMPLIED
 *    WARRANTIES  OF  MERCHANTABILITY,  FITNESS  FOR  A  PARTICULAR
 *    PURPOSE,  AND NON-INFRINGEMENT.  THIS SOFTWARE IS PROVIDED ON
 *    AN "AS IS" BASIS, AND THE AUTHOR  AND  DISTRIBUTORS  HAVE  NO
 *    OBLIGATION   TO   PROVIDE   MAINTENANCE,   SUPPORT,  UPDATES,
 *    ENHANCEMENTS, OR MODIFICATIONS.
 *
 **********************************************************************/

#include "plpgsql.h"


static char	*plpgsql_source;
static int	plpgsql_bytes_left;
static int	scanner_functype;
static int	scanner_typereported;
static int	pushback_token;
static bool have_pushback_token;
static int	lookahead_token;	
static bool have_lookahead_token;

int	plpgsql_SpaceScanned = 0;

static void plpgsql_input(char *buf, int *result, int max);

#define YY_INPUT(buf,res,max)	plpgsql_input(buf, &res, max)
#define YY_NEVER_INTERACTIVE 1
#define YY_NO_UNPUT 1
#define IN_STRING 1
#define IN_COMMENT 2

#line 792 "pl_scan.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 79 "scan.l"

    /* ----------
     * Local variable in scanner to remember where
     * a string or comment started
     * ----------
     */
    int	start_lineno = 0;

    /* ----------
     * Reset the state when entering the scanner
     * ----------
     */
    BEGIN INITIAL;
    plpgsql_SpaceScanned = 0;

    /* ----------
     * On the first call to a new source report the
     * functions type (T_FUNCTION or T_TRIGGER)
     * ----------
     */
	if (!scanner_typereported)
	{
		scanner_typereported = 1;
		return scanner_functype;
	}

    /* ----------
     * The keyword rules
     * ----------
     */
#line 977 "pl_scan.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_more_len = 0;
		if ( yy_more_flag )
			{
			yy_more_len = yy_c_buf_p - yytext_ptr;
			yy_more_flag = 0;
			}
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 338 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 771 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 109 "scan.l"
{ return K_ASSIGN;			}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 110 "scan.l"
{ return K_ASSIGN;			}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 111 "scan.l"
{ return K_DOTDOT;			}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 112 "scan.l"
{ return K_ALIAS;			}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 113 "scan.l"
{ return K_BEGIN;			}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 114 "scan.l"
{ return K_CLOSE;			}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 115 "scan.l"
{ return K_CONSTANT;		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 116 "scan.l"
{ return K_CURSOR;			}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 117 "scan.l"
{ return K_DEBUG;			}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 118 "scan.l"
{ return K_DECLARE;			}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 119 "scan.l"
{ return K_DEFAULT;			}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 120 "scan.l"
{ return K_DIAGNOSTICS;		}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 121 "scan.l"
{ return K_ELSE;			}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 122 "scan.l"
{ return K_ELSIF;           }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 123 "scan.l"
{ return K_END;				}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 124 "scan.l"
{ return K_EXCEPTION;		}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 125 "scan.l"
{ return K_EXECUTE;			}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 126 "scan.l"
{ return K_EXIT;			}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 127 "scan.l"
{ return K_FETCH;			}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 128 "scan.l"
{ return K_FOR;				}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 129 "scan.l"
{ return K_FROM;			}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 130 "scan.l"
{ return K_GET;				}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 131 "scan.l"
{ return K_IF;				}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 132 "scan.l"
{ return K_IN;				}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 133 "scan.l"
{ return K_INFO;			}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 134 "scan.l"
{ return K_INTO;			}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 135 "scan.l"
{ return K_IS;				}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 136 "scan.l"
{ return K_LOG;				}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 137 "scan.l"
{ return K_LOOP;			}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 138 "scan.l"
{ return K_NEXT;			}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 139 "scan.l"
{ return K_NOT;				}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 140 "scan.l"
{ return K_NOTICE;			}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 141 "scan.l"
{ return K_NULL;			}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 142 "scan.l"
{ return K_OPEN;			}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 143 "scan.l"
{ return K_PERFORM;			}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 144 "scan.l"
{ return K_RAISE;			}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 145 "scan.l"
{ return K_RECORD;			}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 146 "scan.l"
{ return K_RENAME;			}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 147 "scan.l"
{ return K_RESULT_OID;		}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 148 "scan.l"
{ return K_RETURN;			}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 149 "scan.l"
{ return K_REVERSE;			}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 150 "scan.l"
{ return K_ROW_COUNT;		}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 151 "scan.l"
{ return K_SELECT;			}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 152 "scan.l"
{ return K_THEN;			}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 153 "scan.l"
{ return K_TO;				}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 154 "scan.l"
{ return K_TYPE;			}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 155 "scan.l"
{ return K_WARNING;			}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 156 "scan.l"
{ return K_WHEN;			}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 157 "scan.l"
{ return K_WHILE;			}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 159 "scan.l"
{ return O_OPTION;			}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 160 "scan.l"
{ return O_DUMP;			}
	YY_BREAK
/* ----------
     * Special word rules
     * ----------
     */
case 52:
YY_RULE_SETUP
#line 167 "scan.l"
{ return plpgsql_parse_word(yytext);	}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 168 "scan.l"
{ return plpgsql_parse_dblword(yytext);	}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 169 "scan.l"
{ return plpgsql_parse_tripword(yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 170 "scan.l"
{ return plpgsql_parse_wordtype(yytext);	}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 171 "scan.l"
{ return plpgsql_parse_dblwordtype(yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 172 "scan.l"
{ return plpgsql_parse_tripwordtype(yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 173 "scan.l"
{ return plpgsql_parse_wordrowtype(yytext);	}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 174 "scan.l"
{ return plpgsql_parse_dblwordrowtype(yytext);	}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 176 "scan.l"
{ return plpgsql_parse_word(yytext);	}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 177 "scan.l"
{ return plpgsql_parse_dblword(yytext);	}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 178 "scan.l"
{ return plpgsql_parse_tripword(yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 179 "scan.l"
{ return plpgsql_parse_wordtype(yytext);	}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 180 "scan.l"
{ return plpgsql_parse_dblwordtype(yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 181 "scan.l"
{ return plpgsql_parse_tripwordtype(yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 182 "scan.l"
{ return plpgsql_parse_wordrowtype(yytext);	}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 183 "scan.l"
{ return plpgsql_parse_dblwordrowtype(yytext);	}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 185 "scan.l"
{ return T_NUMBER;			}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 187 "scan.l"
{
				plpgsql_error_lineno = yylineno;
				elog(ERROR, "unterminated quoted identifier");
			}
	YY_BREAK
/* ----------
     * Ignore whitespaces but remember this happened
     * ----------
     */
case 70:
YY_RULE_SETUP
#line 196 "scan.l"
{ plpgsql_SpaceScanned = 1;		}
	YY_BREAK
/* ----------
     * Eat up comments
     * ----------
     */
case 71:
YY_RULE_SETUP
#line 202 "scan.l"
;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 204 "scan.l"
{ start_lineno = yylineno;
			  BEGIN IN_COMMENT;
			}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 207 "scan.l"
{ BEGIN INITIAL; plpgsql_SpaceScanned = 1; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 208 "scan.l"
;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 209 "scan.l"
;
	YY_BREAK
case YY_STATE_EOF(IN_COMMENT):
#line 210 "scan.l"
{
				plpgsql_error_lineno = start_lineno;
				elog(ERROR, "unterminated comment");
			}
	YY_BREAK
/* ----------
     * Collect anything inside of ''s and return one STRING
     * ----------
     */
case 76:
YY_RULE_SETUP
#line 219 "scan.l"
{ start_lineno = yylineno;
			  BEGIN IN_STRING;
			  yymore();
			}
	YY_BREAK
case 77:
#line 224 "scan.l"
case 78:
YY_RULE_SETUP
#line 224 "scan.l"
{ yymore();				}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 225 "scan.l"
{ BEGIN INITIAL;
			  return T_STRING;
			}
	YY_BREAK
case YY_STATE_EOF(IN_STRING):
#line 228 "scan.l"
{
				plpgsql_error_lineno = start_lineno;
				elog(ERROR, "unterminated string");
			}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 232 "scan.l"
{ yymore();				}
	YY_BREAK
/* ----------
     * Any unmatched character is returned as is
     * ----------
     */
case 81:
YY_RULE_SETUP
#line 238 "scan.l"
{ return yytext[0];			}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 240 "scan.l"
ECHO;
	YY_BREAK
#line 1526 "pl_scan.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 338 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 338 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 337);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 240 "scan.l"



static void
plpgsql_input(char *buf, int *result, int max)
{
    int		n = max;

    if (n > plpgsql_bytes_left)
        n = plpgsql_bytes_left;

    if (n == 0)
	{
        *result = YY_NULL;
		return;
    }

    *result = n;
    memcpy(buf, plpgsql_source, n);
    plpgsql_source += n;
    plpgsql_bytes_left -= n;
}

/*
 * This is the yylex routine called from outside. It exists to provide
 * a pushback facility, as well as to allow us to parse syntax that
 * requires more than one token of lookahead.
 */
int
plpgsql_yylex(void)
{
	int cur_token;

	if (have_pushback_token)
	{
		have_pushback_token = false;
		cur_token = pushback_token;
	}
	else if (have_lookahead_token)
	{
		have_lookahead_token = false;
		cur_token = lookahead_token;
	}
	else
		cur_token = yylex();

	/* Do we need to look ahead for a possible multiword token? */
	switch (cur_token)
	{
		/* RETURN NEXT must be reduced to a single token */
		case K_RETURN:
			if (!have_lookahead_token)
			{
				lookahead_token = yylex();
				have_lookahead_token = true;
			}
			if (lookahead_token == K_NEXT)
			{
				have_lookahead_token = false;
				cur_token = K_RETURN_NEXT;
			}
			break;

		default:
			break;
	}

	return cur_token;
}

/*
 * Push back a single token to be re-read by next plpgsql_yylex() call.
 */
void
plpgsql_push_back_token(int token)
{
	if (have_pushback_token)
		elog(ERROR, "plpgsql_push_back_token: can't push back multiple tokens");
	pushback_token = token;
	have_pushback_token = true;
}


/*
 * Initialize the scanner for new input.
 */
void
plpgsql_setinput(char *source, int functype)
{
    yyrestart(NULL);
    yylineno = 1;

    plpgsql_source = source;

	/*----------
	 * Hack: skip any initial newline, so that in the common coding layout
	 *		CREATE FUNCTION ... AS '
	 *			code body
	 *		' LANGUAGE 'plpgsql';
	 * we will think "line 1" is what the programmer thinks of as line 1.
	 *----------
	 */
    if (*plpgsql_source == '\r')
        plpgsql_source++;
    if (*plpgsql_source == '\n')
        plpgsql_source++;

    plpgsql_bytes_left = strlen(plpgsql_source);

    scanner_functype     = functype;
    scanner_typereported = 0;

	have_pushback_token = false;
	have_lookahead_token = false;
}
