#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for test suites
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /project/eecs/db/cvsroot/postgres/src/test/Makefile,v 1.2 2004/03/24 08:11:36 chungwu Exp $
#
#-------------------------------------------------------------------------

.DEFAULT:
	$(MAKE) -C regress $@
