# $Header: /project/eecs/db/cvsroot/postgres/contrib/array/Makefile,v 1.1.1.2 2003/04/17 22:33:50 sailesh Exp $

subdir = contrib/array
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = array_iterator
DATA_built = array_iterator.sql
DOCS = README.array_iterator

include $(top_srcdir)/contrib/contrib-global.mk
