# $Header: /project/eecs/db/cvsroot/postgres/contrib/isbn_issn/Makefile,v 1.1.1.2 2003/04/17 22:33:51 sailesh Exp $

subdir = contrib/isbn_issn
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = isbn_issn
DATA_built = isbn_issn.sql
DOCS = README.isbn_issn

include $(top_srcdir)/contrib/contrib-global.mk
