# $Header: /project/eecs/db/cvsroot/postgres/contrib/intarray/Makefile,v 1.1.1.2 2003/04/17 22:33:51 sailesh Exp $

subdir = contrib/intarray
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = _int
DATA_built = _int.sql
DOCS = README.intarray
REGRESS = _int

include $(top_srcdir)/contrib/contrib-global.mk
