# $Header: /project/eecs/db/cvsroot/postgres/contrib/earthdistance/Makefile,v 1.1.1.2 2003/04/17 22:37:42 sailesh Exp $

subdir = contrib/earthdistance
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = earthdistance
DATA_built = earthdistance.sql
DOCS = README.earthdistance
REGRESS = earthdistance

include $(top_srcdir)/contrib/contrib-global.mk
