# $Header: /project/eecs/db/cvsroot/postgres/contrib/userlock/Makefile,v 1.1.1.2 2003/04/17 22:37:42 sailesh Exp $

subdir = contrib/userlock
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = user_locks
DATA_built = user_locks.sql
DOCS = README.user_locks

include $(top_srcdir)/contrib/contrib-global.mk
