# $Header: /project/eecs/db/cvsroot/postgres/contrib/tips/Makefile,v 1.1.1.2 2003/04/17 22:34:53 sailesh Exp $

subdir = contrib/tips
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

DOCS = README.apachelog

include $(top_srcdir)/contrib/contrib-global.mk
