# $Header: /project/eecs/db/cvsroot/postgres/contrib/noupdate/Makefile,v 1.1.1.2 2003/04/17 22:33:52 sailesh Exp $

subdir = contrib/noupdate
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = noup
DATA_built = noup.sql
DOCS = README.noup

include $(top_srcdir)/contrib/contrib-global.mk
