#-------------------------------------------------------------------------
#
# $Id: Makefile,v 1.1.1.1 2003/04/17 23:00:53 sailesh Exp $
#
#-------------------------------------------------------------------------
subdir = src/backend/utils/mb/conversion_procs/euc_tw_and_big5
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		:= euc_tw_and_big5

SRCS += big5.c
OBJS += big5.o

include $(srcdir)/../proc.mk
