#-------------------------------------------------------------------------
#
# Makefile for utils
#
# $Header: /project/eecs/db/cvsroot/postgres/src/utils/Makefile,v 1.2 2004/03/24 08:11:38 chungwu Exp $
#
# dllinit.o is only built on Win32 platform.
#
#-------------------------------------------------------------------------

subdir = src/utils
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

all:

clean distclean maintainer-clean:
	rm -f dllinit.o
