# $Header: /project/eecs/db/cvsroot/postgres/contrib/fuzzystrmatch/Makefile,v 1.1.1.2 2003/04/17 22:33:51 sailesh Exp $

subdir = contrib/fuzzystrmatch
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = fuzzystrmatch
DATA_built = fuzzystrmatch.sql
DOCS = README.fuzzystrmatch README.soundex

include $(top_srcdir)/contrib/contrib-global.mk
