# $Header: /project/eecs/db/cvsroot/postgres/contrib/pg_logger/Makefile,v 1.1.1.2 2003/04/17 22:33:53 sailesh Exp $

subdir = contrib/pg_logger
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

PROGRAM = pg_logger
OBJS	= pg_logger.o

DOCS = README.pg_logger

include $(top_srcdir)/contrib/contrib-global.mk
