#-------------------------------------------------------------------------
#
# $Id: Makefile,v 1.1.1.1 2003/04/17 23:00:53 sailesh Exp $
#
#-------------------------------------------------------------------------
subdir = src/backend/utils/mb/conversion_procs/utf8_and_iso8859_1
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		:= utf8_and_iso8859_1

include $(srcdir)/../proc.mk
