# $Header: /project/eecs/db/cvsroot/postgres/contrib/miscutil/Makefile,v 1.1.1.2 2003/04/17 22:33:52 sailesh Exp $

subdir = contrib/miscutil
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = misc_utils
DATA_built = misc_utils.sql
DOCS = README.misc_utils

include $(top_srcdir)/contrib/contrib-global.mk
